### ISSUE TITLE
WXWork: Can not run my demo

### ISSUE THREAD

**Issue by mackwan84** [wechaty/puppet-support#132]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
`const bot = WechatyBuilder.build({
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token: 'puppet_wxwork_?????',
  },
});`

20:35:46 VERB GrpcManager start() starting stream ...
20:35:46 VERB GrpcManager startStream()
20:35:46 VERB GrpcManager startStream() grpc -> event() ...
20:35:46 VERB GrpcManager startStream() grpc -> event() ... done
20:35:46 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...
20:35:49 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout
20:35:49 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked
20:35:49 VERB GrpcManager startStream() initializing event stream ...
20:35:49 VERB GrpcManager startStream() initializing event stream ... done
20:35:49 VERB GrpcManager startStream() ... done
20:35:49 VERB GrpcManager start() starting stream ... done
20:35:49 VERB GrpcManager start() calling grpc server: start() ...
GError: from(`object`): [object Object]
    at Function.from (E:\Projects\wechaty-demo\node_modules\gerror\src\gerror\gerror.ts:77:15)
    at PuppetService.<anonymous> (E:\Projects\wechaty-demo\node_modules\wechaty\src\wechaty-mixins\puppet-mixin.ts:203:41)
    at PuppetService.emit (node:events:390:28)
    at PuppetService.emit (node:domain:475:12)
    at PuppetService.emit (E:\Projects\wechaty-demo\node_modules\wechaty-puppet\src\puppet\puppet-skeleton.ts:137:18)
    at PuppetService.start (E:\Projects\wechaty-demo\node_modules\state-switch\src\service-ctl\service-ctl.ts:98:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetService.start (E:\Projects\wechaty-demo\node_modules\wechaty-puppet\src\mixins\service-mixin.ts:34:7)
    at async WechatyImpl.start (E:\Projects\wechaty-demo\node_modules\wechaty\src\wechaty-mixins\puppet-mixin.ts:81:11)
    at asy

**Comment by huan** [comment]
Can you confirm that your token is valid?

You can use our official tool: [wechaty-token](https://github.com/wechaty/token#wechaty-token-discovery)

**Comment by mackwan84** [comment]
> Can you confirm that your token is valid?
> 
> You can use our official tool: [wechaty-token](https://github.com/wechaty/token#wechaty-token-discovery)

I am sure the token is valid which is created by juzibot.com. For more I do try the official tool and get the response.

**Comment by huan** [comment]
The token will be only valid when the `wechaty-token` says it's valid, no matter who created it because the online status might have networking issues or technical problems anywhere.
